export { default as HomePage } from "./HomePage";
export { default as LoginPage } from "./LoginPage";
export { default as RegisterPage } from "./RegisterPage";
export { default as BrowseProductsPage } from "./BrowseProductsPage";
export { default as MyCartPage } from "./MyCartPage";
export { default as ProfilePage } from "./ProfilePage";
export { default as SingleProductPage } from "./SingleProductPage";
export { default as CheckOutPage } from "./CheckOutPage";
export { default as NotFound } from "./NotFound";
